# Generated by Django 3.1.3 on 2020-11-16 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='quantity',
        ),
    ]
